apiVersion: v1
kind: Service
metadata:
  name: ai-gateway-frontend
  namespace: ai-gateway
spec:
  selector:
    app: ai-gateway-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
